Function Main:Int()
	'LoadTemplate .\templatefile1.monkey, datatype=Float,varname=variable1
	'#Region Code generated by the Harpl-Monkey template. Loaded from: .\templatefile1.monkey
	While<4 Myclass
		For Local Draw:Int = 0 to 100
		'LoadTemplate template2.monkey,name=Float
			For Local i:Int = 0 to 100
				Print "Hello Float, The iteration is " + i
			Next
			'endtemplate
		Next
	End Wend
	'#End Region
	'endtemplate
End Function